# Generated by Django 5.1.11 on 2025-07-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('item_category', models.PositiveSmallIntegerField(choices=[(1, 'NOT_SPECIFIED'), (2, 'BEGINNER_BOARD'), (3, 'INTERMEDIATE_BOARD'), (4, 'ADVANCED_BOARD'), (5, 'SUP'), (6, 'OTHER')], default=1)),
                ('item_state', models.PositiveSmallIntegerField(choices=[(1, 'BOOKABLE'), (2, 'BROKEN'), (3, 'NEED_REPAIR'), (4, 'IS_NO_MORE')], default=1)),
                ('item_size_liter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('reserved_start_time', models.DateTimeField(verbose_name='time booking begins')),
                ('reserved_end_time', models.DateTimeField(verbose_name='time booking ends')),
                ('booking_reference', models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True)),
                ('booked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingitem')),
            ],
        ),
    ]
