log:
  level: INFO

#api:
#  insecure: true

tls:
  certificates:
    - certFile: /certs/domain.cert.pem
      keyFile: /certs/private.key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/domain.cert.pem
        keyFile: /certs/private.key.pem

entryPoints:
  web:
    # http
    address: ':80'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'

http:
  routers:
    web-secure-router:
      rule: 'Host(`surfshed.scraptop.dev`) || Host(`www.scraptop.dev`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      #service: dummy-server
      tls: true

    web-media-router:
      rule: '(Host(`surfshed.scraptop.dev`) || Host(`www.scraptop.dev`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls: true


  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

    dummy-server:
      loadBalancer:
        servers:
          - port: 5678

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
